name: Matrix Demo
on: push
jobs: 
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install NodeJS code
        uses: actions/setup-node@v4.2.0
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build