name: Reusable Deploy
on: 
  workflow_call:
    inputs: 
      artifact-name: 
        description: 'Name of the artifact to deploy'
        required: true
        default: dist
        type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/download-artifact@v4.1.9
        with: 
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy code
        run: echo "Deploying..."