name: Reusable Deploy
on: 
  workflow_call:
    inputs: 
      artifact-name: 
        description: 'Name of the artifact to deploy'
        required: true
        default: dist
        type: string
    # secrets:
    #   some-secret: 
    #     description: 'This is a secret'
    #     required: true
    outputs: 
      result: 
        description: 'The result of the deployment'
        value: ${{ jobs.deploy.outputs.outcome }}
jobs: 
  deploy:
    outputs: 
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/download-artifact@v4.1.9
        with: 
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy code
        run: echo "Deploying..."
      - name: Set Result Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT